name: climatech
description: "ClimaTech - Weather forecast app"
version: 0.1.0+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  http: ^1.2.1
  uuid: ^4.4.0 # UUID token for maps api
  intl: ^0.19.0 # Date format
  material_symbols_icons: ^4.2762.0
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  syncfusion_flutter_datepicker: ^26.1.35
  flutter_spinkit: ^5.2.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  mockito: ^5.4.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/.env
